### ISSUE TITLE
web-app: admin country lists are not sorted

### ISSUE THREAD

**Issue by lynxlynxlynx** [letsdoitworld/World-Cleanup-Day#163]
It boils down to sorting being deliberately disabled:
https://github.com/letsdoitworld/World-Cleanup-Day/blob/e00de0851bb55484967fc0ead27b190381f6737c/backend-db/modules/db/couchdb/index.js#L486
It was this way from the start, so no idea if it was a blind optimisation, an actual issue or something else. @cprpopqual : any memory?

Visible both when listing trashpoints and assigning area admins.

Either way, the two users are not in critical paths, so they can sort the result themselves in their renderInnerAreaList method. Or a level higher in GetAreas: https://github.com/letsdoitworld/World-Cleanup-Day/blob/e00de0851bb55484967fc0ead27b190381f6737c/web-app/src/reducers/areas/operations.js#L24

**Comment by cprpopqual** [comment]
That particular Couch view (`_design/all/_view/view`) is not sorted because it's indexed by document ID, so sorting it would just result in areas sorted by doc ID, which is not useful.

What you want is to create a new design document (in `backend-db/modules/db/couchdb/design/index.js`), next to `designDocs.area.all`, something like `designDocs.area.byName`, and `emit(doc.name, ...)` instead of `doc.id`. Then either modify `getAllAreas()` in `backend-db/modules/db/couchdb/index.js` to use `_design/byName/_view/view` instead of `_design/all/_view/view` (with `{sorted: true}`), or create a separate method that does that. If a different method is created it would have to be called from `backend-db/plugins/areas.js` instead of the other one.

**Comment by lynxlynxlynx** [comment]
Thanks for the insight!

**Comment by KristiinaKerge** [comment]
Aleksandr works with this issue
