### ISSUE TITLE
add suitable map for China

### ISSUE THREAD

**Issue by KristiinaKerge** [letsdoitworld/World-Cleanup-Day#98]
In China googlemap is not usable
http://map.baidu.com/

**Comment by kristiinapalu** [comment]
We can use Baidu map -> develop a different API
2. Implement the API 
4. If Google is providing location-based service, then do we need the same in Baidu as well?
5. If we do, then it could take a while, since we might have no experiance with Baidu APIs.
6. All this together should take 24h of development and can be developed with any developer.

**Comment by KristiinaKerge** [comment]
They have their own mapping app, we can share data.
